[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc = "0.8.26"
via_ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[fuzz]
runs = 256

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
